// Mocks generated by Mockito 5.4.6 from annotations
// in vids_frontend/test/features/download/download_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:async/async.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:stream_channel/stream_channel.dart' as _i3;
import 'package:vids_frontend/features/download/data/repositories/download_repository_impl.dart'
    as _i4;
import 'package:web_socket_channel/web_socket_channel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWebSocketChannel_0 extends _i1.SmartFake
    implements _i2.WebSocketChannel {
  _FakeWebSocketChannel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebSocketSink_1 extends _i1.SmartFake implements _i2.WebSocketSink {
  _FakeWebSocketSink_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamChannel_2<T> extends _i1.SmartFake
    implements _i3.StreamChannel<T> {
  _FakeStreamChannel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadRepository extends _i1.Mock
    implements _i4.DownloadRepository {
  MockDownloadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> getVideoInfo(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoInfo, [url]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String> startDownload(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#startDownload, [url]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#startDownload, [url]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i2.WebSocketChannel trackProgress(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#trackProgress, [taskId]),
            returnValue: _FakeWebSocketChannel_0(
              this,
              Invocation.method(#trackProgress, [taskId]),
            ),
          )
          as _i2.WebSocketChannel);
}

/// A class which mocks [WebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketChannel extends _i1.Mock implements _i2.WebSocketChannel {
  MockWebSocketChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> get ready =>
      (super.noSuchMethod(
            Invocation.getter(#ready),
            returnValue: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.WebSocketSink get sink =>
      (super.noSuchMethod(
            Invocation.getter(#sink),
            returnValue: _FakeWebSocketSink_1(this, Invocation.getter(#sink)),
          )
          as _i2.WebSocketSink);

  @override
  _i5.Stream<dynamic> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<dynamic>.empty(),
          )
          as _i5.Stream<dynamic>);

  @override
  void pipe(_i3.StreamChannel<dynamic>? other) => super.noSuchMethod(
    Invocation.method(#pipe, [other]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.StreamChannel<S> transform<S>(
    _i3.StreamChannelTransformer<S, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [transformer]),
            returnValue: _FakeStreamChannel_2<S>(
              this,
              Invocation.method(#transform, [transformer]),
            ),
          )
          as _i3.StreamChannel<S>);

  @override
  _i3.StreamChannel<dynamic> transformStream(
    _i5.StreamTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformStream, [transformer]),
            returnValue: _FakeStreamChannel_2<dynamic>(
              this,
              Invocation.method(#transformStream, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> transformSink(
    _i7.StreamSinkTransformer<dynamic, dynamic>? transformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transformSink, [transformer]),
            returnValue: _FakeStreamChannel_2<dynamic>(
              this,
              Invocation.method(#transformSink, [transformer]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeStream(
    _i5.Stream<dynamic> Function(_i5.Stream<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeStream, [change]),
            returnValue: _FakeStreamChannel_2<dynamic>(
              this,
              Invocation.method(#changeStream, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<dynamic> changeSink(
    _i5.StreamSink<dynamic> Function(_i5.StreamSink<dynamic>)? change,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeSink, [change]),
            returnValue: _FakeStreamChannel_2<dynamic>(
              this,
              Invocation.method(#changeSink, [change]),
            ),
          )
          as _i3.StreamChannel<dynamic>);

  @override
  _i3.StreamChannel<S> cast<S>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _FakeStreamChannel_2<S>(
              this,
              Invocation.method(#cast, []),
            ),
          )
          as _i3.StreamChannel<S>);
}

/// A class which mocks [WebSocketSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketSink extends _i1.Mock implements _i2.WebSocketSink {
  MockWebSocketSink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> close([int? closeCode, String? closeReason]) =>
      (super.noSuchMethod(
            Invocation.method(#close, [closeCode, closeReason]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  void add(dynamic data) => super.noSuchMethod(
    Invocation.method(#add, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<dynamic> addStream(_i5.Stream<dynamic>? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}
